/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fractal.common;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.event.MouseInputListener;

/**
 *
 * @author CP316928
 */
public class ColorPalette extends javax.swing.JPanel {

    ShowColorChooserListener showColorChooserListener = new ShowColorChooserListener();
    
    JColorChooser cc1 = new JColorChooser();
    JColorChooser cc2 = new JColorChooser();
    JColorChooser cc3 = new JColorChooser();
    JColorChooser cc4 = new JColorChooser();
    
    JPanel p1 = new JPanel();
    JPanel p2 = new JPanel();
    JPanel p3 = new JPanel();
    JPanel p4 = new JPanel();

    /**
     * Creates new form ColorPallet
     */
    public ColorPalette() {
        initComponents();
        setLayout(new GridLayout(1, 4));
        
        p1.setBackground(Color.red);
        p2.setBackground(Color.green);
        p3.setBackground(Color.blue);
        p4.setBackground(Color.black);

        p1.addMouseListener(showColorChooserListener);
        p2.addMouseListener(showColorChooserListener);
        p3.addMouseListener(showColorChooserListener);
        p4.addMouseListener(showColorChooserListener);

        add(p1);
        add(p2);
        add(p3);
        add(p4);
        
    }

    public Color getColor(float a) {
        List<Color> colors = new ArrayList<>();
        colors.add(p1.getBackground());
        colors.add(p2.getBackground());
        colors.add(p3.getBackground());
        colors.add(p4.getBackground());
        
        return ColorInterpolator.interpolate(a, colors);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private class ShowColorChooserListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
//            ColorSelectorDialog d = new ColorSelectorDialog(null, true);
            JDialog d = new JDialog();
            d.setModal(true);
            d.setLayout(new GridLayout(2, 2));
            d.add(cc1);
            d.add(cc2);
            d.add(cc3);
            d.add(cc4);
            
            d.setVisible(true);
            
            p1.setBackground(cc1.getColor());
            p2.setBackground(cc2.getColor());
            p3.setBackground(cc3.getColor());
            p4.setBackground(cc4.getColor());
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
