/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fractal;

import fractal.common.FractalRenderer;
import fractal.common.FractalViewer;
import fractal.mandelbrot.JuliaEngine;
import fractal.mandelbrot.JuliaRenderer;
import fractal.mandelbrot.MandelbrotEngine;
import fractal.mandelbrot.MandelbrotRenderer;
import fractal.mandelbrot.coloring.BandColorCalculator;
import fractal.mandelbrot.coloring.SmoothColorCalculatorMandelbrot;
import java.util.ArrayList;
import java.util.List;
import fractal.common.Antialiasable;
import fractal.mandelbrot.coloring.AverageAngleColorCalculator;
import fractal.mandelbrot.coloring.BuddahColorCalculator;
import fractal.mandelbrot.coloring.ExperimentalColorCalculator;
import fractal.mandelbrot.coloring.SmoothColorCalculatorJulia;
import fractal.newton.NewtonEngine;
import fractal.newton.NewtonRenderer;
import fractal.newton.coloring.NewtonIterationsColorCalculator;
import fractal.newton.coloring.BasinsOfAttractionColorCalulator;

/**
 *
 * @author lloyd
 */
public class main extends javax.swing.JFrame {

    private final FractalRenderer juliaRenderer;
    private final FractalRenderer mandelbrotRenderer;
    private final FractalRenderer newtonRenderer;

    private final List<Antialiasable> antialiasables = new ArrayList<>();

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        mandelbrotRenderer = MandelbrotRenderer.getInstance();
        juliaRenderer = JuliaRenderer.getInstance();
        newtonRenderer = NewtonRenderer.getInstance();
        
        antialiasables.add((Antialiasable) mandelbrotRenderer);
        antialiasables.add((Antialiasable) juliaRenderer);
        antialiasables.add((Antialiasable) newtonRenderer);

//        mandelbrotRenderer.addColorCalculator(new SmoothColorCalculatorMandelbrot(mandelbrotRenderer));
//        mandelbrotRenderer.addColorCalculator(new BandColorCalculator());
//        mandelbrotRenderer.addColorCalculator(new BuddahColorCalculator(mandelbrotRenderer));
//        mandelbrotRenderer.addColorCalculator(new AverageAngleColorCalculator());
//        mandelbrotRenderer.addColorCalculator(new ExperimentalColorCalculator());

//        juliaRenderer.addColorCalculator(new SmoothColorCalculatorJulia(juliaRenderer));
//        juliaRenderer.addColorCalculator(new BandColorCalculator());
//        juliaRenderer.addColorCalculator(new BuddahColorCalculator(juliaRenderer));
//        juliaRenderer.addColorCalculator(new AverageAngleColorCalculator());
//        juliaRenderer.addColorCalculator(new ExperimentalColorCalculator());

//        newtonRenderer.addColorCalculator(new NewtonIterationsColorCalculator(newtonRenderer));
//        newtonRenderer.addColorCalculator(new BasinsOfAttractionColorCalulator());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        mandelbrotButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        juliaButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        newtonButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mandelbrotButton.setText("Draw Mandelbrot");
        mandelbrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandelbrotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mandelbrotButton)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(mandelbrotButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mandelbrot", jPanel1);

        juliaButton.setText("Draw Julia");
        juliaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juliaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(juliaButton)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(juliaButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Julia", jPanel2);

        newtonButton.setText("Draw Newton");
        newtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newtonButton)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(newtonButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Newton", jPanel3);

        jMenu2.setText("Antialiasing");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("None");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setText("2x");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setText("3x");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setText("4x");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mandelbrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandelbrotButtonActionPerformed
        int width = 640;
        int height = 480;
//        mandelbrotRenderer.setFractalEngine(new MandelbrotEngine());
//        mandelbrotRenderer.setFractalViewer(new FractalViewer(mandelbrotRenderer));
        mandelbrotRenderer.getFractalViewer().setVisible(true);

        mandelbrotRenderer.render(width, height, mandelbrotRenderer.getFractalEngine().getDefaultView().getFirst(), mandelbrotRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_mandelbrotButtonActionPerformed

    private void juliaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juliaButtonActionPerformed
        int width = 640;
        int height = 480;
//        juliaRenderer.setFractalEngine(new JuliaEngine());
//        juliaRenderer.setFractalViewer(new FractalViewer(juliaRenderer));
        juliaRenderer.getFractalViewer().setVisible(true);

        juliaRenderer.render(width, height, juliaRenderer.getFractalEngine().getDefaultView().getFirst(), juliaRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_juliaButtonActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem4.setSelected(false);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.NONE);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem4.setSelected(false);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.AA2);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem4.setSelected(false);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.AA3);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem4.setSelected(true);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.AA4);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void newtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtonButtonActionPerformed
        int width = 640;
        int height = 480;
//        newtonRenderer.setFractalEngine(new NewtonEngine());
//        newtonRenderer.setFractalViewer(new FractalViewer(newtonRenderer));
        newtonRenderer.getFractalViewer().setVisible(true);

        newtonRenderer.render(width, height, newtonRenderer.getFractalEngine().getDefaultView().getFirst(), newtonRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_newtonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton juliaButton;
    private javax.swing.JButton mandelbrotButton;
    private javax.swing.JButton newtonButton;
    // End of variables declaration//GEN-END:variables
}
