/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fractal;

import fractal.common.FractalRenderer;
import fractal.mandelbrot.JuliaRenderer;
import fractal.mandelbrot.MandelbrotRenderer;
import java.util.ArrayList;
import java.util.List;
import fractal.common.Antialiasable;
import fractal.newton.NewtonRenderer;
import fractal.phase.henon.HenonRenderer;
import fractal.phase.dejong.DeJongRenderer;
import fractal.walkers.WalkerRenderer;

/**
 *
 * @author lloyd
 */
public class main extends javax.swing.JFrame {

    private static int guiUpdateInterval = 100;//TODO: per renderer
    
    private final FractalRenderer juliaRenderer;
    private final FractalRenderer mandelbrotRenderer;
    private final FractalRenderer newtonRenderer;
    private final HenonRenderer henonRenderer;
    private final DeJongRenderer deJongRenderer;
    private final WalkerRenderer walkerRenderer;

    private final List<Antialiasable> antialiasables = new ArrayList<>();

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        mandelbrotRenderer = MandelbrotRenderer.getInstance();
        juliaRenderer = JuliaRenderer.getInstance();
        newtonRenderer = NewtonRenderer.getInstance();
        henonRenderer = HenonRenderer.getInstance();
        deJongRenderer = DeJongRenderer.getInstance();
        walkerRenderer = WalkerRenderer.getInstance();
        
        antialiasables.add((Antialiasable) mandelbrotRenderer);
        antialiasables.add((Antialiasable) juliaRenderer);
        antialiasables.add((Antialiasable) newtonRenderer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mandelbrotButton = new javax.swing.JButton();
        juliaButton = new javax.swing.JButton();
        newtonButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mandelbrotButton.setText("Draw Mandelbrot");
        mandelbrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandelbrotButtonActionPerformed(evt);
            }
        });

        juliaButton.setText("Draw Julia");
        juliaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juliaButtonActionPerformed(evt);
            }
        });

        newtonButton.setText("Draw Newton");
        newtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtonButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Draw Hennon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Draw Walkers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Draw DeJong");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu2.setText("Antialiasing");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("None");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setText("2x");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setText("3x");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setText("4x");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mandelbrotButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(juliaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newtonButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mandelbrotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(juliaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newtonButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mandelbrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandelbrotButtonActionPerformed
        int width = 1920;
        int height = 1080;
        mandelbrotRenderer.getFractalViewer().setVisible(true);

        mandelbrotRenderer.render(width, height, mandelbrotRenderer.getFractalEngine().getDefaultView().getFirst(), mandelbrotRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_mandelbrotButtonActionPerformed

    private void juliaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juliaButtonActionPerformed
        int width = 1920;
        int height = 1080;
        juliaRenderer.getFractalViewer().setVisible(true);

        juliaRenderer.render(width, height, juliaRenderer.getFractalEngine().getDefaultView().getFirst(), juliaRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_juliaButtonActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem4.setSelected(false);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.NONE);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem4.setSelected(false);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.AA2);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem4.setSelected(false);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.AA3);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem4.setSelected(true);
        for (Antialiasable antialiasable : antialiasables) {
            antialiasable.setAA(Antialiasable.AA4);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void newtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtonButtonActionPerformed
        int width = 1920;
        int height = 1080;
        newtonRenderer.getFractalViewer().setVisible(true);

        newtonRenderer.render(width, height, newtonRenderer.getFractalEngine().getDefaultView().getFirst(), newtonRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_newtonButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int width = 1920;
        int height = 1080;
        henonRenderer.getFractalViewer().setVisible(true);

        henonRenderer.render(width, height, henonRenderer.getFractalEngine().getDefaultView().getFirst(), henonRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int width = 1920;
        int height = 1080;
        walkerRenderer.getFractalViewer().setVisible(true);

        walkerRenderer.render(width, height, walkerRenderer.getFractalEngine().getDefaultView().getFirst(), walkerRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int width = 1920;
        int height = 1080;
        deJongRenderer.getFractalViewer().setVisible(true);

        deJongRenderer.render(width, height, deJongRenderer.getFractalEngine().getDefaultView().getFirst(), deJongRenderer.getFractalEngine().getDefaultView().getSecond());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JButton juliaButton;
    private javax.swing.JButton mandelbrotButton;
    private javax.swing.JButton newtonButton;
    // End of variables declaration//GEN-END:variables

    public static int getGuiUpdateInterval() {
        return guiUpdateInterval;
    }

}
